/*
 * The builder <-> Eleventy boundary, tested ACROSS it.
 *
 * Every other test here looks at one side: the fragment this app writes, or
 * the preview it assembles. The duplicate page ending that shipped until
 * 2026-09-19 lived in neither. Each side was right on its own terms, and the
 * published page — fragment + post_body.njk — showed the date rule and the
 * "← NOTEBOOK FRONT PAGE" link twice. The preview could not show it, because
 * the shell skipped post_body.njk.
 *
 * So this builds a small REAL site: the repo's own eleventy.config.js and
 * layouts, Eleventy from the repo's node_modules, run by Bun with the same
 * Windows fs shim the standalone binaries use. Its pages are exported by this
 * app's code, next to a hand-written block post and a markdown post. Then it
 * checks the published output:
 *
 *   - one header (none of the layout's on a hero page), one ending, one <h1>;
 *   - the preview this app shows IS the published page, body for body
 *     (whitespace aside), against a shell.html generated by the same build;
 *   - balanced <div>s on every kind of page, so a stray close tag in a layout
 *     cannot push the footer out of .bg-topology-map again (post.njk had one);
 *   - a body carrying its own ending — an export from an out-of-date build of
 *     this app — stops the build and names the file.
 */
import { afterAll, describe, expect, test } from "bun:test";
import {
  cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync,
} from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { fileURLToPath } from "url";
import type { Data } from "@measured/puck";
import { config } from "../src/puck/config";
import { DEFAULT_HERO, DEFAULT_META } from "../src/puck/PageRoot";
import { assembleDocument, exportText } from "../src/export/export";
import { renderExportContent, renderExportHero } from "../src/export/renderExport";

const REPO = fileURLToPath(new URL("../../", import.meta.url));
const SITE = "https://haraldrevery.com";
const sites: string[] = [];

/// A throwaway site holding only what a notebook post needs to build.
function makeSite(posts: Record<string, string>, markdown: Record<string, string> = {}): string {
  const dir = mkdtempSync(join(tmpdir(), "pb-site-"));
  sites.push(dir);
  cpSync(join(REPO, "eleventy.config.js"), join(dir, "eleventy.config.js"));
  cpSync(join(REPO, "eleventy_settings"), join(dir, "eleventy_settings"), { recursive: true });
  mkdirSync(join(dir, "eleventy_njk"));
  cpSync(join(REPO, "eleventy_njk", "_builder_shell.njk"), join(dir, "eleventy_njk", "_builder_shell.njk"));
  mkdirSync(join(dir, "input_custom_post"));
  for (const [name, text] of Object.entries(posts)) {
    writeFileSync(join(dir, "input_custom_post", name), text);
  }
  if (Object.keys(markdown).length) {
    mkdirSync(join(dir, "input_markdown"));
    cpSync(
      join(REPO, "input_markdown", "input_markdown.11tydata.js"),
      join(dir, "input_markdown", "input_markdown.11tydata.js"),
    );
    for (const [name, text] of Object.entries(markdown)) {
      writeFileSync(join(dir, "input_markdown", name), text);
    }
  }
  // A junction on Windows: a directory symlink there needs admin rights.
  symlinkSync(join(REPO, "node_modules"), join(dir, "node_modules"), process.platform === "win32" ? "junction" : "dir");
  return dir;
}

function build(dir: string): { ok: boolean; log: string } {
  const r = Bun.spawnSync({
    cmd: [
      process.execPath,
      "--preload", join(REPO, "eleventy_binary", "bun-windows-fs-fix.mjs"),
      join(REPO, "node_modules", "@11ty", "eleventy", "cmd.cjs"),
      "--quiet",
    ],
    cwd: dir,
    stdout: "pipe",
    stderr: "pipe",
  });
  return { ok: r.exitCode === 0, log: r.stdout.toString() + r.stderr.toString() };
}

afterAll(() => {
  for (const dir of sites) rmSync(dir, { recursive: true, force: true });
});

// ------------------------------------------------------------ the pages

const text = (id: string, md: string) => ({ type: "Text", props: { id, md, animate: false, spacing: "normal" } });

const page = (root: Record<string, unknown> = {}): Data =>
  ({
    root: {
      props: {
        meta: { ...DEFAULT_META, title: "Galdhøpiggen & back", date: "2025-08-17", tags: "test", description: "d" },
        hasHero: false,
        hero: DEFAULT_HERO,
        ...root,
      },
    },
    content: [text("t1", "## Section\n\nBody copy.")],
  }) as unknown as Data;

const EXPORTS: Record<string, Data> = {
  plain: page(),
  hero: page({ hasHero: true, hero: { ...DEFAULT_HERO, background: "dots", title: "Galdhøpiggen" } }),
  untitled: page({ meta: { ...DEFAULT_META, title: "", date: "2025-08-17" } }),
};

const parts = (data: Data, slug: string) => ({
  data, config, siteUrl: SITE, slug,
  heroHtml: renderExportHero(data),
  contentHtml: renderExportContent(data),
});

/// Hand-written, the way input_custom_post/README.txt says to. The commented-
/// out ending is the case the build-time guard must NOT trip on.
const HAND_WRITTEN = `---
title: Hand written
date: 2025-08-17
tags: [test]
---
<div class="post-container">
  <article class="prose dark:prose-invert max-w-none mb-16"><p>By hand.</p></article>
</div>
<!-- <a href="/notebook.html" class="x">← NOTEBOOK FRONT PAGE</a> -->
`;

const MARKDOWN = `---
title: Markdown post
date: 2025-08-17
tags: [test]
---
Body paragraph.
`;

/// What every export wrote before 2026-09-19, and what a stale build still does.
const OLD_EXPORT = `---
title: "Old export"
date: 2025-08-17
tags: ["test"]
header: false
customJsonLd: true
---
<p>Body.</p>
  <div class="page-container pt-6">
        <a href="/notebook.html" class="inline-block border-b-2 border-black dark:border-white pb-1 hover:opacity-50 transition text-lg tracking-widest">
          ← NOTEBOOK FRONT PAGE
        </a>
      </div>
`;

// ------------------------------------------------------------ the build

const site = makeSite(
  {
    ...Object.fromEntries(
      Object.entries(EXPORTS).map(([slug, data]) => [`${slug}.html`, exportText(parts(data, slug))]),
    ),
    "hand-written.html": HAND_WRITTEN,
  },
  { "markdown-post.md": MARKDOWN },
);
const result = build(site);

const published = (slug: string) => readFileSync(join(site, "notebook_pages", `${slug}.html`), "utf8");
/// Counts markup, not comments: the hand-written post's commented-out ending
/// is text in the output, but nothing a reader sees.
const count = (s: string, re: RegExp) => (s.replace(/<!--[\s\S]*?-->/g, "").match(re) ?? []).length;
/// The page between base.njk's wrapper and the footer: everything the page
/// builder, post_body.njk and post_chrome.njk contribute.
const pageBody = (html: string) =>
  html.slice(html.indexOf('<div class="bg-topology-map">'), html.indexOf("<footer"));
const norm = (s: string) => s.replace(/\s+/g, " ").replace(/> </g, "><").trim();

describe("the published site", () => {
  test("builds", () => {
    expect(result.log).not.toContain("Error");
    expect(result.ok).toBe(true);
  });

  test.each([
    // slug, h1s, back links (the layout's, or the hero's own)
    ["plain", 1, 1],
    ["hero", 1, 1],
    ["untitled", 0, 1],
    ["hand-written", 1, 1],
    ["markdown-post", 1, 1],
  ])("%s: one ending, and the header exactly once", (slug, h1s, backLinks) => {
    const html = published(slug);
    expect(count(html, /NOTEBOOK FRONT PAGE/g)).toBe(1);
    expect(count(html, /<hr>/g)).toBe(1);
    expect(count(html, /<h1/g)).toBe(h1s);
    expect(count(html, /← Back to Notebook/g)).toBe(backLinks);
  });

  test("a hero page gets no layout header — the hero is its header", () => {
    expect(published("hero")).not.toContain("mb-8 pb-8 border-b");
    expect(published("plain")).toContain("mb-8 pb-8 border-b");
  });

  test.each(["plain", "hero", "untitled", "hand-written", "markdown-post"])(
    "%s: every <div> closes, so the footer stays inside .bg-topology-map",
    (slug) => {
      const html = published(slug);
      expect(count(html, /<div\b/g)).toBe(count(html, /<\/div>/g));
      const footer = html.indexOf("<footer");
      expect(html.indexOf('<div class="bg-topology-map">')).toBeLessThan(footer);
      // the wrapper's closing tag is the last </div> and comes after the footer
      expect(html.lastIndexOf("</div>")).toBeGreaterThan(html.indexOf("</footer>"));
    },
  );
});

describe("the preview is the published page", () => {
  const shell = () => readFileSync(join(site, "page_builder_app_v2", "shell.html"), "utf8");

  // Not "untitled": its preview shows "Untitled" as the heading while the
  // published page has none — a known difference, and the page check warns.
  test.each(["plain", "hero"])("%s", (slug) => {
    const preview = assembleDocument({ ...parts(EXPORTS[slug], slug), shell: shell() });
    expect(norm(pageBody(preview))).toBe(norm(pageBody(published(slug))));
  });
});

describe("a body that carries its own ending", () => {
  const old = makeSite({ "old-export.html": OLD_EXPORT });
  const r = build(old);

  test("stops the build, naming the file and the fix", () => {
    expect(r.ok).toBe(false);
    expect(r.log).toContain("old-export.html");
    expect(r.log).toContain("NOTEBOOK FRONT PAGE");
    expect(r.log).toContain("export the page again");
  });
});
