use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;
use tauri::State;
use tauri_plugin_dialog::DialogExt;

use crate::{repo, AppState};

const SITE_URL: &str = "https://haraldrevery.com";

/// Repo folder that exported pages are written to (Eleventy reads it as
/// BUILD_PAGE_DIR in eleventy.config.js). Renaming that folder = change this
/// one line and rebuild.
///
/// Pages here are BODY FRAGMENTS with YAML front matter, not whole documents.
/// Eleventy wraps each one in eleventy_settings/base.njk, which supplies the
/// <head>, nav.njk and footer.njk at build time. The extension is .njk because
/// "html" is not in Eleventy's templateFormats, so a .html file here would never
/// be picked up as a template — and the directory data file sets
/// templateEngineOverride: false so the body is emitted verbatim and never
/// parsed as a template.
///
/// input_custom_html_pages/ still exists for complete standalone documents (the
/// browser apps and rare one-offs); this app no longer writes there.
const BUILD_PAGE_DIR: &str = "input_build_page";

/// This app's own folder inside the repo — holds `projects/` and `shell.html`.
/// Deliberately NOT shared with v1's `page_builder/`: the project formats are
/// incompatible (v1 stores {version,meta,blocks}, v2 stores Puck Data).
///
/// `shell.html` here is BUILD OUTPUT, generated by
/// eleventy_njk/_builder_shell.njk on every site build, and is used only for the
/// in-app preview. Do not edit it; edit eleventy_settings/nav.njk, footer.njk or
/// base.njk. Renaming this folder = change this one line, the permalink in that
/// template, and rebuild.
const APP_DIR: &str = "page_builder_app_v2";

fn repo_root(state: &State<AppState>) -> Result<PathBuf, String> {
    state
        .root
        .read()
        .map_err(|_| "state poisoned".to_string())?
        .clone()
        .ok_or_else(|| "Site repo not located".to_string())
}

/// Resolve a root-absolute web path (/photos/foo.jpg) to a canonical
/// filesystem path, verifying it stays inside the repo — symlinks (and any
/// `..` in the path) cannot escape. None = missing or outside the repo.
fn resolve_in_repo(root: &Path, web: &str) -> Option<PathBuf> {
    let file = fs::canonicalize(root.join(web.trim_start_matches('/'))).ok()?;
    let canon_root = fs::canonicalize(root).ok()?;
    file.starts_with(&canon_root).then_some(file)
}

/// Write via a sibling temp file + fsync + rename, so the destination is either
/// the old contents or the new ones — never a truncated or half-written file.
/// Plain `fs::write` truncates first, so a crash, a full disk or a power loss
/// mid-write destroys the previous contents with nothing to recover from. Used
/// for every write the app makes: projects, exported pages and shell.html.
fn write_atomic(path: &Path, contents: &str) -> Result<(), String> {
    use std::io::Write;
    let dir = path
        .parent()
        .ok_or_else(|| format!("{} has no parent directory", path.display()))?;
    let tmp = path.with_extension(format!(
        "{}.tmp",
        path.extension().and_then(|e| e.to_str()).unwrap_or("")
    ));
    let write = || -> std::io::Result<()> {
        let mut f = fs::File::create(&tmp)?;
        f.write_all(contents.as_bytes())?;
        f.sync_all()?; // durable before the rename, or the rename can win a race
        Ok(())
    };
    if let Err(e) = write() {
        let _ = fs::remove_file(&tmp);
        return Err(format!("Cannot write {}: {e}", tmp.display()));
    }
    // rename is atomic within a filesystem; tmp is a sibling so that holds
    fs::rename(&tmp, path).map_err(|e| {
        let _ = fs::remove_file(&tmp);
        format!("Cannot replace {}: {e}", path.display())
    })?;
    let _ = dir; // dir handle only needed on platforms that fsync directories
    Ok(())
}

// ---------------------------------------------------------------- config

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Config {
    pub repo_root: Option<String>,
    pub preview_port: u16,
    pub site_url: String,
}

#[tauri::command]
pub fn get_config(state: State<AppState>) -> Config {
    let root = state.root.read().ok().and_then(|g| g.clone());
    Config {
        repo_root: root.map(|p| p.display().to_string()),
        preview_port: state.port,
        site_url: SITE_URL.to_string(),
    }
}

/// Folder picker used when auto-discovery fails; validates and persists.
#[tauri::command]
pub async fn locate_repo(
    app: tauri::AppHandle,
    state: State<'_, AppState>,
) -> Result<Option<String>, String> {
    let picked = app.dialog().file().blocking_pick_folder();
    let Some(folder) = picked else {
        return Ok(None);
    };
    let path = folder
        .into_path()
        .map_err(|e| format!("Invalid folder: {}", e))?;
    if !repo::validate_repo_root(&path) {
        return Err(format!(
            "{} does not look like the site repo (needs eleventy.config.js and eleventy_settings/)",
            path.display()
        ));
    }
    repo::persist_repo_root(&path);
    if let Ok(mut guard) = state.root.write() {
        *guard = Some(path.clone());
    }
    Ok(Some(path.display().to_string()))
}

// ---------------------------------------------------------------- media

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PickedFile {
    pub web: String,
    pub full: String,
    pub thumb: String,
    pub thumb_exists: bool,
    pub width: Option<u32>,
    pub height: Option<u32>,
}

/// Pixel dimensions of an image inside the repo (header-only read).
fn dims_of(root: &Path, web: &str) -> Option<(u32, u32)> {
    let file = resolve_in_repo(root, web)?;
    imagesize::size(&file)
        .ok()
        .map(|s| (s.width as u32, s.height as u32))
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PickResult {
    pub files: Vec<PickedFile>,
    pub rejected: Vec<String>,
}

/// Absolute filesystem path -> root-absolute web path (/photos/...).
fn web_path_from_abs(abspath: &Path, root: &Path) -> Option<String> {
    let rel = abspath.strip_prefix(root).ok()?;
    let s = rel
        .components()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/");
    Some(format!("/{}", s))
}

fn split_ext(web: &str) -> (&str, &str) {
    match web.rfind('.') {
        Some(i) if i > web.rfind('/').unwrap_or(0) => (&web[..i], &web[i..]),
        _ => (web, ""),
    }
}

fn in_repo_is_file(root: &Path, web: &str) -> bool {
    root.join(web.trim_start_matches('/')).is_file()
}

/// The _min thumbnail convention: foo.jpg is the full-size (lightbox href),
/// foo_min.jpg the grid thumbnail. Missing _min falls back to the full-size
/// image and is flagged so the UI can show a warning badge instead of failing.
///
/// BOTH branches check the disk. Deriving the full-size path from a picked
/// `_min` file used to be unconditional, so picking a thumbnail whose
/// full-size twin does not exist produced a dangling lightbox href — reported
/// to the UI as `thumb_exists: true`, i.e. with a green tick. When the twin is
/// missing the picked file becomes both full and thumb: the link then works,
/// and `thumb_exists: false` tells the truth (no distinct thumbnail is in use).
fn derive_full_thumb(web: &str, root: &Path) -> (String, String, bool) {
    let (base, ext) = split_ext(web);
    if base.ends_with("_min") {
        let full = format!("{}{}", &base[..base.len() - 4], ext);
        if in_repo_is_file(root, &full) {
            (full, web.to_string(), true)
        } else {
            (web.to_string(), web.to_string(), false)
        }
    } else {
        let cand = format!("{}_min{}", base, ext);
        let exists = in_repo_is_file(root, &cand);
        let thumb = if exists { cand } else { web.to_string() };
        (web.to_string(), thumb, exists)
    }
}

#[tauri::command]
pub async fn pick_media(
    app: tauri::AppHandle,
    state: State<'_, AppState>,
    kind: String,
    multiple: bool,
    start_dir: Option<String>,
) -> Result<PickResult, String> {
    let root = repo_root(&state)?;

    let filters: &[(&str, &[&str])] = match kind.as_str() {
        "image" => &[("Images", &["jpg", "jpeg", "png", "webp", "gif", "svg", "avif"])],
        "svg" => &[("SVG", &["svg"])],
        "video" => &[("Video", &["mp4", "webm"])],
        "audio" => &[("Audio", &["mp3", "wav", "ogg", "m4a"])],
        _ => &[],
    };

    let start = start_dir
        .map(|d| root.join(d))
        .filter(|d| d.is_dir())
        .unwrap_or_else(|| root.clone());

    let mut dialog = app.dialog().file().set_directory(start);
    for (name, exts) in filters {
        dialog = dialog.add_filter(*name, exts);
    }

    let picked: Vec<tauri_plugin_dialog::FilePath> = if multiple {
        dialog.blocking_pick_files().unwrap_or_default()
    } else {
        dialog.blocking_pick_file().into_iter().collect()
    };

    let mut files = Vec::new();
    let mut rejected = Vec::new();
    for fp in picked {
        let Ok(path) = fp.into_path() else { continue };
        match web_path_from_abs(&path, &root) {
            Some(web) => {
                let (full, thumb, thumb_exists) = derive_full_thumb(&web, &root);
                // ratio comes from the full-size image; fall back to the picked file
                let dims = dims_of(&root, &full).or_else(|| dims_of(&root, &web));
                files.push(PickedFile {
                    web,
                    full,
                    thumb,
                    thumb_exists,
                    width: dims.map(|d| d.0),
                    height: dims.map(|d| d.1),
                });
            }
            None => rejected.push(path.display().to_string()),
        }
    }
    Ok(PickResult { files, rejected })
}

/// Batch existence check for root-absolute web paths (thumb revalidation on load).
#[tauri::command]
pub fn check_files(state: State<AppState>, paths: Vec<String>) -> Result<Vec<bool>, String> {
    let root = repo_root(&state)?;
    Ok(paths
        .iter()
        .map(|p| resolve_in_repo(&root, p).is_some_and(|f| f.is_file()))
        .collect())
}

/// Batch pixel-dimension lookup (justified galleries need aspect ratios).
#[tauri::command]
pub fn image_dims(
    state: State<AppState>,
    paths: Vec<String>,
) -> Result<Vec<Option<(u32, u32)>>, String> {
    let root = repo_root(&state)?;
    Ok(paths.iter().map(|p| dims_of(&root, p)).collect())
}

// ---------------------------------------------------------------- file hashes

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FileHashInfo {
    pub size: u64,
    pub sha256: String,
    pub sha512: String,
}

/// Streamed SHA-256 + SHA-512 in one pass (1 MiB chunks — large zips/videos
/// never load into memory). MD5 is deliberately not offered.
fn hash_one(root: &Path, web: &str) -> Option<FileHashInfo> {
    use sha2::{Digest, Sha256, Sha512};
    use std::io::Read;
    let file = resolve_in_repo(root, web)?;
    let mut f = fs::File::open(&file).ok()?;
    let size = f.metadata().ok()?.len();
    let mut h256 = Sha256::new();
    let mut h512 = Sha512::new();
    let mut buf = vec![0u8; 1024 * 1024];
    loop {
        let n = f.read(&mut buf).ok()?;
        if n == 0 {
            break;
        }
        h256.update(&buf[..n]);
        h512.update(&buf[..n]);
    }
    Some(FileHashInfo {
        size,
        sha256: format!("{:x}", h256.finalize()),
        sha512: format!("{:x}", h512.finalize()),
    })
}

/// Batch hashing for the downloads block; None per missing/unreadable file.
#[tauri::command]
pub fn hash_files(
    state: State<AppState>,
    paths: Vec<String>,
) -> Result<Vec<Option<FileHashInfo>>, String> {
    let root = repo_root(&state)?;
    Ok(paths.iter().map(|p| hash_one(&root, p)).collect())
}

/// Read an .svg file from inside the repo (for themed inlining in the
/// renderer). Path is a root-absolute web path like /svg/foo.svg.
#[tauri::command]
pub fn read_svg(state: State<AppState>, path: String) -> Result<String, String> {
    if !path.to_ascii_lowercase().ends_with(".svg") {
        return Err("Only .svg files can be inlined".to_string());
    }
    let root = repo_root(&state)?;
    let file = resolve_in_repo(&root, &path)
        .ok_or_else(|| format!("Cannot read {}: missing or outside the repo", path))?;
    fs::read_to_string(&file).map_err(|e| format!("Cannot read {}: {}", path, e))
}

// ---------------------------------------------------------------- projects

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectInfo {
    pub name: String,
    pub modified: u64,
}

fn projects_dir(root: &Path) -> PathBuf {
    root.join(APP_DIR).join("projects")
}

fn sanitize_project_name(name: &str) -> Result<String, String> {
    let clean: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect();
    if clean.is_empty() {
        return Err("Project name must contain letters, digits, - or _".to_string());
    }
    Ok(clean)
}

#[tauri::command]
pub fn list_projects(state: State<AppState>) -> Result<Vec<ProjectInfo>, String> {
    let dir = projects_dir(&repo_root(&state)?);
    let mut out = Vec::new();
    if let Ok(entries) = fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("json") {
                let name = path
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_default();
                let modified = entry
                    .metadata()
                    .ok()
                    .and_then(|m| m.modified().ok())
                    .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                    .map(|d| d.as_secs())
                    .unwrap_or(0);
                out.push(ProjectInfo { name, modified });
            }
        }
    }
    out.sort_by(|a, b| b.modified.cmp(&a.modified));
    Ok(out)
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveResult {
    pub written: bool,
    pub exists: bool,
    /// The sanitized stem that actually names the file. The caller must adopt
    /// this: "My Photos" becomes "MyPhotos", and keeping the raw string made the
    /// title bar disagree with the Open list.
    pub name: String,
    pub path: String,
}

#[tauri::command]
pub fn save_project(
    state: State<AppState>,
    name: String,
    data: String,
    overwrite: bool,
) -> Result<SaveResult, String> {
    let dir = projects_dir(&repo_root(&state)?);
    fs::create_dir_all(&dir).map_err(|e| format!("Cannot create {}: {e}", dir.display()))?;
    let clean = sanitize_project_name(&name)?;
    let file = dir.join(format!("{clean}.json"));
    // Sanitizing is lossy, so distinct titles can collide onto one file. Without
    // this check the second save silently destroyed the first.
    let existed = file.exists();
    if existed && !overwrite {
        return Ok(SaveResult {
            written: false,
            exists: true,
            name: clean,
            path: file.display().to_string(),
        });
    }
    write_atomic(&file, &data)?;
    Ok(SaveResult {
        written: true,
        exists: existed, // whether it was already there, not whether it is now
        name: clean,
        path: file.display().to_string(),
    })
}

#[tauri::command]
pub fn load_project(state: State<AppState>, name: String) -> Result<String, String> {
    let file = projects_dir(&repo_root(&state)?).join(format!("{}.json", sanitize_project_name(&name)?));
    fs::read_to_string(&file).map_err(|e| format!("Cannot read {}: {}", file.display(), e))
}

// ---------------------------------------------------------------- export

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ExportResult {
    pub written: bool,
    pub exists: bool,
    pub path: String,
}

#[tauri::command]
pub fn export_page(
    state: State<AppState>,
    file_name: String,
    contents: String,
    overwrite: bool,
) -> Result<ExportResult, String> {
    if file_name.contains('/') || file_name.contains('\\') || !file_name.ends_with(".njk") {
        return Err("Export file name must be a plain *.njk name".to_string());
    }
    let dir = repo_root(&state)?.join(BUILD_PAGE_DIR);
    fs::create_dir_all(&dir).map_err(|e| format!("Cannot create {}: {e}", dir.display()))?;
    let file = dir.join(&file_name);
    let existed = file.exists();
    if existed && !overwrite {
        return Ok(ExportResult {
            written: false,
            exists: true,
            path: file.display().to_string(),
        });
    }
    write_atomic(&file, &contents)?;
    Ok(ExportResult {
        written: true,
        exists: existed, // report what actually happened, not a fixed false
        path: file.display().to_string(),
    })
}

/*
 * Save the page as a COMPLETE standalone document, wherever the user points the
 * native Save dialog. None = the dialog was cancelled.
 *
 * The ONLY write this app makes outside the repo, and deliberately so. The
 * normal export writes a body fragment into input_build_page/ for Eleventy to
 * wrap, and a whole document has no place there. It has no place in
 * input_custom_html_pages/ either, even though that is where v1 wrote and where
 * the site keeps standalone documents: Eleventy publishes that folder, so a page
 * exported both ways would go live twice, under two URLs, with two canonicals
 * pointing at one of them.
 *
 * The frontend never supplies a path — only a suggested file name, which is
 * stripped to a bare stem here so it cannot smuggle a directory into the
 * dialog. The destination is whatever the user picks, so there is nothing to
 * jail: they are choosing it in their own file manager.
 */
#[tauri::command]
pub async fn save_html_document(
    app: tauri::AppHandle,
    state: State<'_, AppState>,
    file_name: String,
    contents: String,
) -> Result<Option<String>, String> {
    // Suggestion only; the dialog is free to be renamed. Strip any directory
    // part rather than rejecting it — this is a hint, not a destination.
    let stem = file_name
        .rsplit(['/', '\\'])
        .next()
        .unwrap_or("")
        .trim_end_matches(".html")
        .trim();
    let suggested = if stem.is_empty() { "page" } else { stem };

    let mut dialog = app
        .dialog()
        .file()
        .add_filter("HTML", &["html"])
        .set_file_name(format!("{suggested}.html"));
    // Start in the repo when we have one — the usual destination is next to the
    // site, and a dialog that opens in $HOME every time is a papercut.
    if let Ok(root) = repo_root(&state) {
        dialog = dialog.set_directory(root);
    }

    let Some(picked) = dialog.blocking_save_file() else {
        return Ok(None);
    };
    let path = picked
        .into_path()
        .map_err(|e| format!("Invalid destination: {e}"))?;
    // GTK's save dialog returns exactly what was typed, extension or not; the
    // filter does not append one. A file called "postcard" would open in a text
    // editor rather than a browser, so give it the extension it is missing.
    let path = if path.extension().is_none() {
        path.with_extension("html")
    } else {
        path
    };
    write_atomic(&path, &contents)?;
    Ok(Some(path.display().to_string()))
}

// ---------------------------------------------------------------- preview

/// Upper bound on the in-memory preview document. A real page is tens of KB;
/// this only exists so a runaway Raw block cannot pin an unbounded string for
/// the lifetime of the app.
const MAX_PREVIEW_BYTES: usize = 4 * 1024 * 1024;

/// Hand the rendered page to the server thread for GET /__pb/preview.
///
/// Memory only — previewing must never write to the repo, which is the whole
/// point of having it. An empty string clears the slot, so closing the modal
/// releases the document.
#[tauri::command]
pub fn set_preview_html(state: State<AppState>, contents: String) -> Result<(), String> {
    if contents.len() > MAX_PREVIEW_BYTES {
        return Err(format!(
            "Preview document is {} bytes; the limit is {}",
            contents.len(),
            MAX_PREVIEW_BYTES
        ));
    }
    let mut slot = state
        .preview
        .write()
        .map_err(|_| "state poisoned".to_string())?;
    *slot = (!contents.is_empty()).then_some(contents);
    Ok(())
}

// ------------------------------------------------------------- recovery
//
// A periodic snapshot of unsaved work, so a crash or a power loss does not cost
// the session. Three rules keep it from being able to damage anything:
//
//   1. It lives in the config dir, never in the repo — see repo::recovery_file.
//   2. It is written with write_atomic like every other write here, so a crash
//      DURING the snapshot cannot leave a half-written draft that then fails to
//      parse on the one occasion it is needed.
//   3. Rust never parses it. The payload shape belongs to the frontend, and a
//      draft this app cannot understand is a draft it must not act on, so the
//      contents pass through as an opaque string.

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryInfo {
    pub contents: String,
    /// Unix seconds, so the restore prompt can say how old the draft is.
    pub modified: u64,
}

#[tauri::command]
pub fn write_recovery(contents: String) -> Result<(), String> {
    let path = repo::recovery_file().ok_or("No config directory available")?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Cannot create {}: {e}", parent.display()))?;
    }
    write_atomic(&path, &contents)
}

/// None = nothing to recover. A draft that cannot be READ is reported as None
/// rather than as an error: the caller is booting, and a missing safety net
/// must never be the thing that stops the app from starting.
#[tauri::command]
pub fn read_recovery() -> Result<Option<RecoveryInfo>, String> {
    let Some(path) = repo::recovery_file() else {
        return Ok(None);
    };
    let Ok(contents) = fs::read_to_string(&path) else {
        return Ok(None);
    };
    let modified = fs::metadata(&path)
        .ok()
        .and_then(|m| m.modified().ok())
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_secs())
        .unwrap_or(0);
    Ok(Some(RecoveryInfo { contents, modified }))
}

/// Called once the work is safe (saved, or replaced by an open/new). Already
/// gone is success, not an error — the draft only ever needs to not exist.
#[tauri::command]
pub fn clear_recovery() -> Result<(), String> {
    let Some(path) = repo::recovery_file() else {
        return Ok(());
    };
    match fs::remove_file(&path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(format!("Cannot remove {}: {e}", path.display())),
    }
}

#[tauri::command]
pub fn read_shell(state: State<AppState>) -> Result<String, String> {
    let file = repo_root(&state)?.join(APP_DIR).join("shell.html");
    fs::read_to_string(&file).map_err(|e| format!("Cannot read {}: {}", file.display(), e))
}

// The shell-freshness check that used to live here is gone, and so is the
// staleness it detected. page_builder_app_v2/shell.html is now GENERATED by
// eleventy_njk/_builder_shell.njk from the same nav.njk / footer.njk that
// every other page uses, so it is refreshed on every site build and cannot
// drift. It is only used for the in-app preview; exported pages are body
// fragments wrapped by base.njk at build time.
//
// The old check diffed shell.html against input_custom_html_pages/
// galdhopiggen.html — itself a builder-produced page carrying the same stale
// chrome — so it compared a stale copy to a stale copy and never fired.

#[cfg(test)]
mod tests {
    use super::{derive_full_thumb, hash_one};

    /// Regression: the `_min` branch used to derive the full-size path without
    /// checking the disk, so picking a thumbnail whose full-size twin is absent
    /// produced a dangling lightbox href — and reported it as thumb_exists:true,
    /// i.e. a green tick in the sidebar.
    #[test]
    fn picking_a_min_file_never_yields_a_dangling_full_size_path() {
        let dir = std::env::temp_dir().join("pb_derive_full_thumb");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("photos")).unwrap();

        // A pair: both files present.
        std::fs::write(dir.join("photos/pair.jpg"), b"x").unwrap();
        std::fs::write(dir.join("photos/pair_min.jpg"), b"x").unwrap();
        // An orphan thumbnail, like photos/audioplayer_texture3_min.webp.
        std::fs::write(dir.join("photos/orphan_min.webp"), b"x").unwrap();
        // A full-size image with no thumbnail yet.
        std::fs::write(dir.join("photos/lonely.jpg"), b"x").unwrap();

        // Picking either half of a real pair resolves to the same pair.
        assert_eq!(
            derive_full_thumb("/photos/pair_min.jpg", &dir),
            ("/photos/pair.jpg".into(), "/photos/pair_min.jpg".into(), true)
        );
        assert_eq!(
            derive_full_thumb("/photos/pair.jpg", &dir),
            ("/photos/pair.jpg".into(), "/photos/pair_min.jpg".into(), true)
        );

        // The orphan becomes both full and thumb: the link works, and the flag
        // says false because no distinct thumbnail is in use.
        assert_eq!(
            derive_full_thumb("/photos/orphan_min.webp", &dir),
            ("/photos/orphan_min.webp".into(), "/photos/orphan_min.webp".into(), false)
        );

        // Unchanged behaviour: no _min yet, fall back to the full-size image.
        assert_eq!(
            derive_full_thumb("/photos/lonely.jpg", &dir),
            ("/photos/lonely.jpg".into(), "/photos/lonely.jpg".into(), false)
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn hashes_match_known_sha2_test_vectors() {
        // NIST test vector: message "abc"
        let dir = std::env::temp_dir().join("pb_hash_test");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("abc.txt"), b"abc").unwrap();
        let info = hash_one(&dir, "abc.txt").unwrap();
        assert_eq!(info.size, 3);
        assert_eq!(
            info.sha256,
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            info.sha512,
            "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a\
             2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f"
        );
        assert!(hash_one(&dir, "missing.bin").is_none());
    }

    #[test]
    fn write_atomic_replaces_contents_and_leaves_no_temp_file() {
        let dir = std::env::temp_dir().join("pb_write_atomic_ok");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join("project.json");

        super::write_atomic(&file, "first").unwrap();
        assert_eq!(std::fs::read_to_string(&file).unwrap(), "first");

        super::write_atomic(&file, "second").unwrap();
        assert_eq!(std::fs::read_to_string(&file).unwrap(), "second");

        // no .tmp sibling survives a successful write
        let leftovers: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.contains("tmp"))
            .collect();
        assert!(leftovers.is_empty(), "temp files left behind: {leftovers:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_atomic_leaves_the_original_intact_when_it_cannot_write() {
        // the destination directory does not exist, so File::create fails
        let dir = std::env::temp_dir().join("pb_write_atomic_fail");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join("keep.json");
        std::fs::write(&file, "original").unwrap();

        let missing = dir.join("nope").join("keep.json");
        assert!(super::write_atomic(&missing, "new").is_err());
        // the pre-existing file is untouched — the whole point of temp+rename
        assert_eq!(std::fs::read_to_string(&file).unwrap(), "original");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
